### ISSUE TITLE
Issue related to migrating triggers on live database

### ISSUE THREAD

**Issue by JoharAlam** [esign/laravel-database-trigger#1]
Hi,

Hope you are doing well. I am facing an issue related to triggers migration. Actually on local when I run migration command it create triggers perfectly without any error but on production when I try to migrate trigger is shows below error:

SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable) (Connection: tenant, SQL: create trigger update_question before update on questions for each row begin INSERT INTO question_histories (que_id, que_desc,que_type,que_field, created_at) VALUES ( OLD.id, OLD.question, OLD.type_id,OLD.fieldType, LOCALTIME()); end;)

If I go with the possible solutions as mentioned in above error then this will make database unsafe and anyone with the database credentials can do whatever he want to do.

Do you have any solution of this in your repo?

**Comment by jordyvanderhaegen** [comment]
Hi, as mentioned by the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/create-trigger.html) your user might require the SUPER privilege if you have binary logging enabled:
>[CREATE TRIGGER](https://dev.mysql.com/doc/refman/8.0/en/create-trigger.html) requires the [TRIGGER](https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_trigger) privilege for the table associated with the trigger. If the DEFINER clause is present, the privileges required depend on the user value, as discussed in [Section 25.6, “Stored Object Access Control”](https://dev.mysql.com/doc/refman/8.0/en/stored-objects-security.html). If binary logging is enabled, [CREATE TRIGGER](https://dev.mysql.com/doc/refman/8.0/en/create-trigger.html) might require the [SUPER](https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_super) privilege, as discussed in [Section 25.7, “Stored Program Binary Logging”](https://dev.mysql.com/doc/refman/8.0/en/stored-programs-logging.html).

This doesn't seem to be a problem with this package, so I'll be closing this issue.
Feel free to open a new issue if you feel like it is.
